import './globals.css';

import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';

import Footer from '@/components/common/footer';
import Header from '@/components/common/header';

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={figtree.className}>
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="my-12 flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
